Fix multiple critical issues in README.md
redcap3000/crypto-socket pull request #9
Opened 2018-04-27 12:33 UTC by hatarist

2018-04-27 12:34 UTC, BEaStia requested changes

2018-04-27 12:34 UTC, BEaStia commented on README.md
>  Nope. Ticker values (in most cases last sale price) is stored in memory.
Are stored

2018-04-27 12:37 UTC, BEaStia approved these changes

2018-04-27 12:45 UTC, BEaStia commented
you're picot

2018-04-27 19:42 UTC, redcap3000 commented
I will require at least 5 other reviewers before I can confidently review the changes requested. It would also help if these reviewers had at least starred this repo. Thank you.

2018-04-27 19:57 UTC, faustinoaq approved these changes

2018-04-28 00:14 UTC, QuickBASIC requested changes

2018-04-28 00:14 UTC, QuickBASIC commented on README.md
> +As of now, **Poloniex** exchange only has one open socket that sends back all data. The above syntax is not recommeneded unless you are only following one symbol, as it will open up multiple sockets
s/`returns`/`will return`

2018-04-28 00:14 UTC, QuickBASIC commented on README.md
> +A simple printout of all opened ticker quotes.
s/`opened`/`open`

Changing this doesn't add any clarity; "open ticker quotes" are ticker quotes that are open (referring to at the current time) not ticker quotes that were at some point in the past opened.

2018-04-28 00:14 UTC, QuickBASIC commented on README.md
> +This module **does not include exchange API's that do not have web sockets**. Why? There's a billion other modules that do something similar, and perhaps this is a wake up call to any exchange that d
s/`There's`/`There are`

We're referring to multiple items (billions of modules).

2018-04-28 03:35 UTC, Dobermensch requested changes
Make changes as requested in comments

2018-04-28 05:01 UTC, redcap3000 commented
Well well. Russian Trolls at their finest. If anyone wants to continue to nitpick my README I'm more than open to changes.

2018-04-28 19:22 UTC, redcap3000 approved these changes
redcap3000 approves these changes.

2018-04-28 19:23 UTC, merged

2018-04-28 19:26 UTC, redcap3000 commented
So anyone here know javascript? Maybe we can correct the actual code or someone can write some much needed unit tests. As robotic as I am; I am unable to evaluate myself in a programmatic fashion. Thank you!